### Importing Necessary Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sb

### Reading the data

In [26]:
data=pd.read_csv("data.csv")

To show all columns

In [27]:
pd.set_option("display.max_columns",None)

In [33]:
data[:20]

,ClaimNumber,DateTimeOfAccident,DateReported,Age,Gender,MaritalStatus,DependentChildren,DependentsOther,WeeklyWages,PartTimeFullTime,HoursWorkedPerWeek,DaysWorkedPerWeek,ClaimDescriptionKeyword_0,ClaimDescriptionKeyword_1,ClaimDescriptionKeyword_2,ClaimDescriptionKeyword_3,ClaimDescriptionKeyword_4,ClaimDescriptionKeyword_5,ClaimDescriptionKeyword_6,ClaimDescriptionKeyword_7,ClaimDescriptionKeyword_8,ClaimDescriptionKeyword_9,ClaimDescriptionKeyword_10,ClaimDescriptionKeyword_11,InitialIncurredClaimsCost,UltimateIncurredClaimCost
0,WC8285054,2002-04-09T07:00:00Z,2002-07-05T00:00:00Z,48,M,M,0,0,500.00,F,38.0,5,2.254325,-1.466085,-1.278155,-0.422165,-0.137039,1.634239,-1.436096,-0.757871,-1.091920,0.880767,0.168497,1.161294,1500,4748.203388
1,WC6982224,1999-01-07T11:00:00Z,1999-01-20T00:00:00Z,43,F,M,0,0,509.34,F,37.5,5,2.356002,-1.259903,1.490410,-0.818467,1.788994,0.459482,0.662757,-0.240500,-0.162451,0.665242,0.844019,-1.305332,5500,6326.285819
2,WC5481426,1996-03-25T00:00:00Z,1996-04-14T00:00:00Z,30,M,U,0,0,709.10,F,38.0,5,0.817685,-1.088115,1.520340,-0.233031,-0.045712,-0.192742,-0.047881,0.139051,-0.339551,-0.386420,-0.397919,-0.259750,1700,2293.949087
3,WC9775968,2005-06-22T13:00:00Z,2005-07-22T00:00:00Z,41,M,S,0,0,555.46,F,38.0,5,4.022864,3.184172,-0.014604,1.219356,0.067053,1.105471,0.609462,1.495272,-0.527257,-0.187209,-0.857031,-0.343594,15000,17786.487170
4,WC2634037,1990-08-29T08:00:00Z,1990-09-27T00:00:00Z,36,M,M,0,0,377.10,F,38.0,5,3.383056,0.009941,1.691871,-1.390378,-0.647481,-1.413973,-0.807369,0.243139,1.031237,0.366183,0.427945,-0.038234,2800,4014.002925
5,WC6828422,1999-06-21T11:00:00Z,1999-09-09T00:00:00Z,50,M,M,0,0,200.00,F,38.0,5,1.133906,-0.476469,0.341175,1.551529,0.638735,-0.997512,1.572472,-0.734540,0.026355,0.865337,0.499820,0.261544,500,598.762315
6,WC8058150,2001-07-13T11:00:00Z,2001-07-23T00:00:00Z,39,M,M,0,0,200.00,F,38.0,5,1.775247,-1.550651,1.453080,-0.097094,0.576316,0.774661,-1.021066,0.577168,0.232907,-0.481077,0.433796,-0.735375,500,279.068178
7,WC7539849,2000-03-09T09:00:00Z,2000-04-16T00:00:00Z,56,M,M,0,0,200.00,F,40.0,5,2.744255,-1.929976,2.900141,-0.992026,-0.062384,0.333227,-1.533217,1.128924,1.151813,1.051162,-0.839323,-0.460803,500,1877.172243
8,WC4427179,1994-03-24T16:00:00Z,1994-04-26T00:00:00Z,49,M,M,0,0,623.60,F,38.0,5,3.069126,-1.300793,1.676072,1.842426,-1.603341,0.615196,-1.951648,0.913573,0.470693,-1.401308,1.365177,-0.357116,925,1254.129811
9,WC9907636,2005-12-07T11:00:00Z,2005-12-22T00:00:00Z,30,M,S,0,0,857.28,F,37.0,5,1.666143,-1.027949,1.601195,-0.278150,-0.155960,-0.236267,1.741857,-0.282733,-0.151194,0.516169,0.229539,0.275402,1500,1031.603044
10,WC3053943,1991-04-11T17:00:00Z,1991-04-22T00:00:00Z,20,M,S,0,0,480.77,F,40.0,5,4.767350,3.935170,-0.175116,-0.650020,0.805077,-0.687802,1.196387,0.382781,-0.329139,-1.317050,0.582406,0.228658,3500,4464.016322
11,WC6193926,1997-07-09T13:00:00Z,1997-07-25T00:00:00Z,22,M,S,0,0,200.00,F,38.0,5,1.574887,-2.175615,-2.451475,-1.041988,-0.206258,-0.436447,0.247814,0.487674,-1.278116,0.166805,-0.567980,0.234415,1000,1343.513498
12,WC2826510,1990-11-13T11:00:00Z,1990-11-21T00:00:00Z,29,M,S,0,0,391.80,F,38.0,5,1.126503,0.615003,0.050351,0.593070,-0.322346,0.922787,-0.132728,-0.167130,-0.504200,0.472522,0.215110,0.163231,250,736.035014
13,WC5428872,1996-12-09T08:00:00Z,1996-12-17T00:00:00Z,25,M,S,0,0,386.18,F,38.0,5,1.685950,-0.745519,-1.263975,0.040638,0.067544,-0.425826,0.706556,0.650366,-0.484623,0.894723,0.733397,-0.460579,1300,945.395532
14,WC4129793,1993-09-23T06:00:00Z,1993-10-25T00:00:00Z,17,M,S,0,0,515.00,F,38.0,5,0.897354,-0.195115,-0.001899,-0.602246,-1.939981,1.599352,1.219472,-0.894308,1.187787,-0.440879,0.070609,0.024639,735,407.091915
15,WC8342953,2002-01-30T09:00:00Z,2002-02-07T00:00:00Z,58,M,M,0,0,525.00,F,40.0,5,2.798642,-0.180169,-1.457137,-0.669630,-0.059474,-1.573759,-0.224472,1.248943,1.486985,0.259201,-0.353655,-0.214833,25000,105285.148600
16,WC3379929,1991-05-08T11:00:00Z,1991-05-10T00:00:00Z,52,M,M,0,0,347.15,F,36.0,5,3.034465,-1.916853,0.127598,-0.587881,0.944825,-0.290441,0.065147,1.463669,1.113504,1.866566,-0.059356,-1.010828,3500,1888.450077
17,WC2798133,1990-08-28T15:00:00Z,1990-09-29T00:00:00Z,17,M,S,0,0,200.00,F,38.0,5,2.522550,-2.797162,-0.918704,1.874432,1.705136,0.536268,-0.195592,-0.825777,0.975452,-0.937141,-0.668863,-0.198850,1000,566.883307
18,WC4302308,1993-01-18T11:00:00Z,1993-02-09T00:00:00Z,17,M,S,0,0,320.00,F,40.0,5,1.396146,-0.436246,0.209330,1.573613,-1.266114,0.507141,-1.533608,-0.265697,0.496603,-0.696988,0.656695,-0.650997,3500,2054.868515
19,WC5202252,1995-03-15T13:00:00Z,1995-05-01T00:00:00Z,27,M,S,0,0,200.00,F,38.0,5,2.366984,-1.976370,1.878374,2.026474,-1.260672,-0.398042,-0.457123,-0.466961,-0.068447,-0.686216,-0.346744,0.551887,500,230.616918

### Works to be done in Cleaning process
- **Drop ClaimNumber** Column as it is not useful for the prediction.
- Remove **Time** values from **T** in **DateTimeOfAccident** and **DateReported**.
- Change Datatype of **DateTimeOfAccident** and **DateReported** to **datetime64**.
- Count the **Total.No.Of.Days** between **DateTimeOfAccident** and **DateReported** and make a **newcolumn** with datatype as **int**.

In [29]:
data.shape

(54000, 26)

In [30]:
data.dtypes

ClaimNumber                    object
DateTimeOfAccident             object
DateReported                   object
Age                             int64
Gender                         object
MaritalStatus                  object
DependentChildren               int64
DependentsOther                 int64
WeeklyWages                   float64
PartTimeFullTime               object
HoursWorkedPerWeek            float64
DaysWorkedPerWeek               int64
ClaimDescriptionKeyword_0     float64
ClaimDescriptionKeyword_1     float64
ClaimDescriptionKeyword_2     float64
ClaimDescriptionKeyword_3     float64
ClaimDescriptionKeyword_4     float64
ClaimDescriptionKeyword_5     float64
ClaimDescriptionKeyword_6     float64
ClaimDescriptionKeyword_7     float64
ClaimDescriptionKeyword_8     float64
ClaimDescriptionKeyword_9     float64
ClaimDescriptionKeyword_10    float64
ClaimDescriptionKeyword_11    float64
InitialIncurredClaimsCost       int64
UltimateIncurredClaimCost     float64
dtype: object

In [31]:
data.isnull().sum()

ClaimNumber                    0
DateTimeOfAccident             0
DateReported                   0
Age                            0
Gender                         0
MaritalStatus                 29
DependentChildren              0
DependentsOther                0
WeeklyWages                    0
PartTimeFullTime               0
HoursWorkedPerWeek             0
DaysWorkedPerWeek              0
ClaimDescriptionKeyword_0      0
ClaimDescriptionKeyword_1      0
ClaimDescriptionKeyword_2      0
ClaimDescriptionKeyword_3      0
ClaimDescriptionKeyword_4      0
ClaimDescriptionKeyword_5      0
ClaimDescriptionKeyword_6      0
ClaimDescriptionKeyword_7      0
ClaimDescriptionKeyword_8      0
ClaimDescriptionKeyword_9      0
ClaimDescriptionKeyword_10     0
ClaimDescriptionKeyword_11     0
InitialIncurredClaimsCost      0
UltimateIncurredClaimCost      0
dtype: int64

**Droping** the column **ClaimNumber**

In [34]:
data.drop("ClaimNumber",1,inplace=True)

In [35]:
data

,DateTimeOfAccident,DateReported,Age,Gender,MaritalStatus,DependentChildren,DependentsOther,WeeklyWages,PartTimeFullTime,HoursWorkedPerWeek,DaysWorkedPerWeek,ClaimDescriptionKeyword_0,ClaimDescriptionKeyword_1,ClaimDescriptionKeyword_2,ClaimDescriptionKeyword_3,ClaimDescriptionKeyword_4,ClaimDescriptionKeyword_5,ClaimDescriptionKeyword_6,ClaimDescriptionKeyword_7,ClaimDescriptionKeyword_8,ClaimDescriptionKeyword_9,ClaimDescriptionKeyword_10,ClaimDescriptionKeyword_11,InitialIncurredClaimsCost,UltimateIncurredClaimCost
0,2002-04-09T07:00:00Z,2002-07-05T00:00:00Z,48,M,M,0,0,500.00,F,38.0,5,2.254325,-1.466085,-1.278155,-0.422165,-0.137039,1.634239,-1.436096,-0.757871,-1.091920,0.880767,0.168497,1.161294,1500,4748.203388
1,1999-01-07T11:00:00Z,1999-01-20T00:00:00Z,43,F,M,0,0,509.34,F,37.5,5,2.356002,-1.259903,1.490410,-0.818467,1.788994,0.459482,0.662757,-0.240500,-0.162451,0.665242,0.844019,-1.305332,5500,6326.285819
2,1996-03-25T00:00:00Z,1996-04-14T00:00:00Z,30,M,U,0,0,709.10,F,38.0,5,0.817685,-1.088115,1.520340,-0.233031,-0.045712,-0.192742,-0.047881,0.139051,-0.339551,-0.386420,-0.397919,-0.259750,1700,2293.949087
3,2005-06-22T13:00:00Z,2005-07-22T00:00:00Z,41,M,S,0,0,555.46,F,38.0,5,4.022864,3.184172,-0.014604,1.219356,0.067053,1.105471,0.609462,1.495272,-0.527257,-0.187209,-0.857031,-0.343594,15000,17786.487170
4,1990-08-29T08:00:00Z,1990-09-27T00:00:00Z,36,M,M,0,0,377.10,F,38.0,5,3.383056,0.009941,1.691871,-1.390378,-0.647481,-1.413973,-0.807369,0.243139,1.031237,0.366183,0.427945,-0.038234,2800,4014.002925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53995,2004-08-21T18:00:00Z,2004-09-08T00:00:00Z,32,F,S,0,0,500.00,F,38.0,5,3.227811,-2.498176,3.272976,1.009275,0.671885,-0.551931,0.609996,0.004547,-0.080993,0.244063,0.633730,-1.078211,1000,480.493308
53996,2002-04-28T09:00:00Z,2002-09-03T00:00:00Z,20,F,S,0,0,500.00,F,40.0,5,3.538016,-3.211951,4.924040,-0.754216,2.316328,0.649956,0.760474,-0.230762,-0.971785,0.310966,-1.879551,-0.299992,1000,755.735319
53997,1992-02-28T09:00:00Z,1992-03-18T00:00:00Z,19,M,S,0,0,283.00,F,40.0,5,0.971563,-0.536971,0.131402,1.118753,-0.493861,0.217121,-0.487354,0.445688,0.847410,-1.123457,0.687752,0.087566,210,418.178461
53998,1995-01-10T07:00:00Z,1995-01-31T00:00:00Z,24,M,S,0,0,200.00,F,38.0,5,2.728639,-2.128230,-0.945860,2.439972,-1.191801,-0.380672,-0.589854,-0.078175,0.266576,-0.823754,-0.266269,0.199324,7500,2695.225700
53999,1990-10-24T14:00:00Z,1990-11-03T00:00:00Z,22,M,S,0,0,200.00,F,38.0,5,2.044998,-2.422213,1.894573,1.540520,0.668117,0.077269,-0.169170,-0.724550,0.250203,-1.210799,0.137591,0.356837,550,934.273548

In [13]:
data[data["MaritalStatus"]=="U"]["MaritalStatus"].count()

5294

In [36]:
data["MaritalStatus"]=data["MaritalStatus"].fillna("U")

In [41]:
data["MaritalStatus"].value_counts().sum()

54000

In [42]:
data.isnull().sum()

DateTimeOfAccident            0
DateReported                  0
Age                           0
Gender                        0
MaritalStatus                 0
DependentChildren             0
DependentsOther               0
WeeklyWages                   0
PartTimeFullTime              0
HoursWorkedPerWeek            0
DaysWorkedPerWeek             0
ClaimDescriptionKeyword_0     0
ClaimDescriptionKeyword_1     0
ClaimDescriptionKeyword_2     0
ClaimDescriptionKeyword_3     0
ClaimDescriptionKeyword_4     0
ClaimDescriptionKeyword_5     0
ClaimDescriptionKeyword_6     0
ClaimDescriptionKeyword_7     0
ClaimDescriptionKeyword_8     0
ClaimDescriptionKeyword_9     0
ClaimDescriptionKeyword_10    0
ClaimDescriptionKeyword_11    0
InitialIncurredClaimsCost     0
UltimateIncurredClaimCost     0
dtype: int64

In [50]:
data[data["Age"]==0]["Age"].count()

0